### ISSUE TITLE
Documenting private R6 methods throws warning

### ISSUE THREAD

**Issue by s-fleck** [r-lib/roxygen2#1016]
Documenting a private R6 method throws a `@description Cannot find matching R6 method` warning. IMHO this should mimic the behaviour of documenting unexported functions of a package and create documentation for the method in question, except if suppressed via `@noRd`

**Comment by gaborcsardi** [comment]
It cannot really mimic that behavior, because methods do not have manual pages, there is one page for the whole class.

**Comment by s-fleck** [comment]
Hmm can't we just get a **private methods** section for the class doc? Though for me it's more about getting rid of the warning... of course I could just remove the roxygen comment completely, but this would be a nicer beavhiour in my oppionion

**Comment by gaborcsardi** [comment]
Considering that private methods are not part of the private API usually, and this is the end user documentation (usually), I don't think we should show a "private methods" section.

If you just want to get rid of the warning, you can use `#` comments instead of `#'`. 

We might consider creating internal docs that also include the private methods, but would need to think about that a bit first.

**Comment by s-fleck** [comment]
ok thanks :)
