### ISSUE TITLE
Order of @includeRmd custom sections and pkgdown pages

### ISSUE THREAD

**Issue by nteetor** [r-lib/roxygen2#1032]
When building a reference topic page, pkgdown lays out sections according to the order found in the original rd file. Currently `@includeRmd` places custom sections at the bottom of an rd file if the section is not a part of an existing section. In my example, the custom section included appears after the "see also" section (alternatively the "see also" section comes before the custom section).

![image](https://user-images.githubusercontent.com/3228369/72655295-e5e7b500-3961-11ea-8d32-8af77b5c4116.png)

I think a solution for #988 would nullify this problem. Custom sections could be manually placed and the contents of include rmd would be added to the existing sections.

**Comment by hadley** [comment]
@gaborcsardi how hard would this be to do?

**Comment by gaborcsardi** [comment]
There are two issues here I think. One is to be able to include an Rmd _into_ a user defined `@section`, that is #988 as I understand.

The other is the order of `@includeRmd` sections in the generated Rd file, because even though the order is ignored by base R, it will be upheld by pkgdown. (Is that right?) This seems to be an easy fix, so I'll do it before the release.
