### ISSUE TITLE
Custom Roclet - Document how to give our roclet options

### ISSUE THREAD

**Issue by matthewstrasiotto** [r-lib/roxygen2#1138]
In [The roclet section](https://roxygen2.r-lib.org/articles/extending.html#the-roclet) of the "Extending Roxygen" vignette, you tell us:

https://github.com/r-lib/roxygen2/blob/c73def498f29783044fe50865f22c2482f80942d/vignettes/extending.Rmd#L261-L270

This tells me that roclets CAN take options, if you want them to. 

What I don't see documented is the correct way to do so - I wonder if this can be documented somewhere?

The following suggests I can simply add new fields to roclet using the constructor.

```r
my_roclet <- roxygen2::roclet("my_roclet", info = "hello")
my_roclet
# $info
# [1] "hello"
# 
# attr(,"class")
# [1] "roclet_my_roclet" "roclet" 
```

The following suggests that I can call my roclet with its params using `roclets = list("my_package::my_roclet(param1 = "hello")`

https://github.com/r-lib/roxygen2/blob/c73def498f29783044fe50865f22c2482f80942d/R/roclet.R#L77-L115

I also wonder - How would I use this roclet's options in actual usage of the roclet?

From the [roclet function docs](https://roxygen2.r-lib.org/reference/roclet.html#arguments), it seems that we can access our roclet's fields, as our roclet is passed as the first argument of each `roclet_method()`

https://github.com/r-lib/roxygen2/blob/c73def498f29783044fe50865f22c2482f80942d/vignettes/extending.Rmd#L283-L298

In each of your examples, you don't even touch the first argument, `x`, but it looks like I can use `x$param1` to get the "hello" I passed in for my roclet.

I wonder if these docs could be expanded to explain this.

**Comment by mstr3336** [comment]
Having spoken on all of this - 

My use-case for passing params to my roclets was that I wanted to be able to override the destination to which serialized tag data is written. 

An example of this:

For package `journeyr`, the default might be:

`"inst/columns/journeyr.yaml"`

I also intend to implement a tag that enabled one to inherit column docs from another package, using the other package's serialized columns, for example, if i had a package called `pipeliner`, it might have a tag

```r
#' @inherit_cols journeyr <optional specification of columns to inherit, API undecided>
```

And by default, would find `journeyr`'s `"inst/columns/journeyr.yaml"`, read that, and then place that in its own `"inst/columns/"` dir. 

It looks like `roclet` arguments would be a poor way to accomplish setting this path for each package, and I'd instead be better off using `roxygen2` options, so that I can do the following:

```r
default_column_path <- function(package_name) {
  file.path("inst/columns", paste0(package_name, ".yaml"))

}

inherit_package_columns(package_name) {
  package_options <- roxygen2::load_options(system.file(package = package_name))
  column_path <- package_options$column_path
  
  if (rlang::is_empty(column_path) column_path <- default_column_path(package_name)

 # and so on ( I dont have time to work through this example)
}
```

Is this correct, though?

**Comment by matthewstrasiotto** [comment]
By the way, I resolved this in one way or another, I used the roxygen meta construct. 

See my package [mandrake](https://github.com/matthewstrasiotto/mandrake) for an example
