### ISSUE TITLE
automatically mark documentation for un-exported functions as internal?

### ISSUE THREAD

**Issue by kevinushey** [r-lib/roxygen2#1185]
Currently, if a function is documented but not exported, that documentation is still added to the package index. Could `roxygen2` implicitly infer that documentation associated with an un-exported function should be marked as internal?

**Comment by condwanaland** [comment]
Personally I'd love to see this feature. I like to document all my functions, even if unexported, and I often forget to add the @noRd tag (or equivalent).

**Comment by jpkrooney** [comment]
There is/was a way to do this using @keywords internal (https://github.com/r-lib/roxygen2/issues/684). But its not working for me so I don't know if there is a bug ?

**Comment by gaborcsardi** [comment]
@kevinushey This is not that simple unfortunately, because manual pages can have arbitrary names. E.g. a manual page called `foobar` may document functions `foo` or `bar`. Or it may just document an aspect of the package, without documenting any actual functions or objects.

So just because there is no `foobar()` function in the package, that does not mean that people do not want to have the `foobar` page in the manual index.

We could have some smarter way to try to guess whether a page should be in the index or not, but honestly I am not sure if it is worth complicating the rules. It would almost certainly be a breaking change, and also breaking the wrong way. (Pages suddenly omitted from the index in the new roxygen2 version.) OTOH it is pretty easy to add `@keywords internal` to an internal page.

Maybe as a compromise roxygen2 could warn for pages that _probably should have_ `@keywords internal` because they don't have a corresponding exported function? Maybe with the ability to turn the warnings off with a package option?

@jpkrooney `@keywords internal` definitely works for many people, here is a guide: https://blog.r-hub.io/2019/12/12/internal-functions/ If it does not work for you, then please open an issue with a reproducible example. Thanks!

**Comment by jpkrooney** [comment]
Thanks @gaborcsardi. It is actually working now except for one file. Not sure what happened but I will figure that out 👍

**Comment by hadley** [comment]
Yeah, I think unfortunately implementing this robustly would be a lot of work and the benefits are relatively small. (If you're following `usethis::use_release_issue()` you should spot the problem when you review the reference page of the website)
