### ISSUE TITLE
Inherit the same section from multiple functions

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/roxygen2#1198]
Reprex: 

```r
temp_pkg <- file.path(tempdir(), "test")
usethis::create_package(temp_pkg, open = FALSE)

source <- "
#' Function f
#'
#' @examples
#' f()
f <- function() {
  message('I am f')
}
#' Function g
#' 
#' @examples
#' g()
g <- function() {
  message('I am g')
}
#' Function h
#' 
#' @inherit f examples
#' @inherit g examples
h <- function() {
  message('I am h')
}
"

write(source, file.path(temp_pkg, "R", "test.R"))

roxygen2::roxygenise(temp_pkg)

file.show(file.path(temp_pkg, "man", "h.Rd"))
```

In `h.Rd`, I would like to see 

```
\examples{
f()
g()
}
```

instead of 

```
\examples{
f()
}
```

In other words, when the same section is inherited from multiple functions, the result should be concatenated to create the new section.

This would be particularly useful to gather references from multiple functions in a single place.

**Comment by hadley** [comment]
Is this about sections in general or examples in particular? (i.e. I have a vague feeling that this might only affect examples).

**Comment by Bisaloo** [comment]
My personal use case would be examples and references.

A wrapper for multiple other exported functions could benefit from collecting their references.

**Comment by hadley** [comment]
Right, but can you verify that it fails for other types? (not just examples?)

**Comment by Bisaloo** [comment]
I can confirm the same happens with references and return

**Comment by hadley** [comment]
Thanks!

**Comment by dschlaep** [comment]
I am having the same/similar use cases. I love the capability to re-use documentation with the different "inherit" options. However, re-use functionality would be even more useful if it could inherit references from multiple functions (this issue; example `foo3` below; instead of ignoring all but the first inherited instance) and to add (instead of ignore) inherited references if references are already present (example `foo4` below).

``` r
packageVersion("roxygen2")
#> [1] '7.1.2.9000'

roxygen2::roc_proc_text(
  roxygen2::rd_roclet(),  "
  #' Title1
  #' @references Author1 reference
  foo1 <- function(x) {}

  #' Title2
  #' @references Author2 reference
  foo2 <- function(x) {}

  #' Title3
  #' @inherit foo1 references
  #' @inherit foo2 references
  foo3 <- function(x) {}

  #' Title4
  #' @inherit foo3 references
  #' @references Author4 reference
  foo4 <- function(x) {}
")
#> $foo1.Rd
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{foo1}
#> \alias{foo1}
#> \title{Title1}
#> \usage{
#> foo1(x)
#> }
#> \description{
#> Title1
#> }
#> \references{
#> Author1 reference
#> }
#> 
#> $foo2.Rd
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{foo2}
#> \alias{foo2}
#> \title{Title2}
#> \usage{
#> foo2(x)
#> }
#> \description{
#> Title2
#> }
#> \references{
#> Author2 reference
#> }
#> 
#> $foo3.Rd
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{foo3}
#> \alias{foo3}
#> \title{Title3}
#> \usage{
#> foo3(x)
#> }
#> \description{
#> Title3
#> }
#> \references{
#> Author1 reference
#> }
#> 
#> $foo4.Rd
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{foo4}
#> \alias{foo4}
#> \title{Title4}
#> \usage{
#> foo4(x)
#> }
#> \description{
#> Title4
#> }
#> \references{
#> Author4 reference
#> }
```

<sup>Created on 2022-02-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

For `foo3`, I would like to see 
```r
#> \references{
#> Author1 reference
#> Author2 reference
#> }
```

For `foo4`, I would like to see 
```r
#> \references{
#> Author1 reference
#> Author2 reference
#> Author4 reference
#> }
```

**Comment by hadley** [comment]
I now realise that we probably shouldn't change this because it would make the way inherits works inconsistent — in general, we only inherit "missing" things that are present in the current topic. I can see why it would be useful to include multiple things from different docs, but my gut feeling is that it would introduce more problems than it solves.
