### ISSUE TITLE
Allow `Roxygen: list()` to include a vector of tags that are exempted from markdown parsing

### ISSUE THREAD

**Issue by wviechtb** [r-lib/roxygen2#1215]
Package authors may define macros different from the 'official' tags listed here (https://github.com/r-lib/roxygen2/blob/master/R/markdown-escaping.R#L38) for which it may also be desirable to avoid markdown parsing. Case in point, the `mathjaxr` package (https://github.com/wviechtb/mathjaxr) provides an easy way for package authors to include equations in their documentation that are parsed via MathJax in the html help files. The package provides several macros such as `\mjeqn` and `\mjdeqn` for this purpose. Unfortunately, markdown parsing (e.g., when there is an underline/underscore for a subscript) can happen within these tags (see: https://github.com/wviechtb/mathjaxr/issues/7). A possible solution would be to allow the specification of additional tags via `Roxygen: list()` in `DESCRIPTION` that are also exempted from markdown parsing (in essence, these just need to be appended to `escaped_for_md`). Would there be interest in adding such an option to `roxygen2`?

**Comment by gaborcsardi** [comment]
Maybe we could just add these tags to the list instead of providing an API that every user using these macros would need to use.

**Comment by wviechtb** [comment]
If you are happy to add the tags from `mathjaxr` to that list (they are: `\mjeqn`, `\mjdeqn`, `\mjseqn`, `\mjsdeqn`, `\mjteqn`, `\mjtdeqn`), then I would of course be more than happy with that as well.

**Comment by jpquast** [comment]
I have a similar problem as described in this blog post (which I think started this issue): https://githubmemory.com/repo/wviechtb/mathjaxr/issues/7

I use `Roxygen: list(markdown = TRUE)` because I want to use the `lifecycle` package in my package, which prompted me to turn this on.

Maybe I am missing something but I do not seem to be able to escape underscores. In a `@param` tag I am writing roughly the following: 

```
#' @param comparison Comparisons need to be in the form condition1_vs_condition2, meaning two compared 
#' conditions are separated by "_vs_". 
```

Markdown parsing creates `"\emph{vs}"` out of the `"_vs_"`. 
I tried escaping the underscores with `\` but this just creates: `"\\emph{vs\}"`

Is there a way I can correctly escape this? I am sorry if this is a bit off topic for this issue. 
Maybe I am just misunderstanding something and there is an easy way to avoid this. 
Help would be very much appreciated! Thanks a lot!

**Comment by wviechtb** [comment]
@jpquast You could use `\code{"_vs_"}` or some other tag for which no markdown parsing is done.

**Comment by jpquast** [comment]
@wviechtb True! That is indeed a solution to the problem. I wonder if there is any more correct way to solve this since it is not actually code. But I will use this for now! Thanks for the quick reply!

**Comment by gaborcsardi** [comment]
There are a number of ways to do this:
- Only turn on Markdown for selected chunks, with `@md`.
- Turn off Markdown for selected chunks, with `@noMd`.
- Use `\out{}` which is emitted untouched. One difficulty with this is that it is also untouched by base R's Rd tools, and you need to protect `_` in LaTeX, but not in HTML and plain text. So you need something like this:
    ```
    ... by "\ifelse{latex}{\out{\_vs\_}}{\out{_vs_}}".
    ```
