### ISSUE TITLE
https://github.com/MislavSag/finfeatures

### ISSUE THREAD

**Issue by MislavSag** [r-lib/roxygen2#1267]
I have described my problem with ` roxygen2` in the following stackowerflow question: https://stackoverflow.com/questions/69785961/devtolls-document-function-doesnt-create-namespace-file.

For some reason, `devtools::document()` doesn't crate NAMESPACE file.

Here is my Github repo:
https://github.com/MislavSag/finfeatures

**Comment by gaborcsardi** [comment]
This is a chicken and egg problem. roxygen needs to load the package to create a `NAMESPACE` file, but it cannot load the package because there is no `NAMESPACE` file and you are using functions from other packages outside of your function definitions, e.g. these:

```
RollingGpd = R6Class
```

Replace `R6Class` with `R6::R6Class` and then roxygen can load the package.

**Comment by MislavSag** [comment]
I have added `R6::` to all files that use `R6` class and it works now.

I was following structure of mlr3 package: https://github.com/mlr-org/mlr3/tree/main/R.
I am just curious. Why they didn't have to use `R6::` before R6 classes?

**Comment by gaborcsardi** [comment]
Now that you have a proper `NAMESPACE` file roxygen2 can load the package (assuming you import `R6Class()` in `NAMESPACE`), so you don't need the `R6::` prefix any more. 

All this is really only needed because R6 is a build-time dependency in your package.
