### ISSUE TITLE
Consider enabling autolink extension in markdown_xml

### ISSUE THREAD

**Issue by jeroen** [r-lib/roxygen2#1474]
The gfm autolink extension will automatically detects URLs and email addresses in markdown text and turn them into hyperlinks. See [gfm-autolink spec](https://github.github.com/gfm/#autolinks-extension-) for details.

https://github.com/r-lib/roxygen2/blob/a34bdf7c7b952068b1f7742b7b34d1eac78e54da/R/markdown.R#L213-L216

Additional benefit is that this prevents a URLs from getting spell-checked as if they were plain text.

**Comment by hadley** [comment]
Yeah, sounds like a good idea.

**Comment by hadley** [comment]
I tried turning this on and it broke a test because surprisingly it will autolink the url in this text:

```
#' [link % text](https://foo.bar/link%20target)
```

This is probably not coming from commonmark directly, but something we're for our hybrid Rd-md mode, but either way I don't think it's worth running down in more depth as the parser is already pretty fragile.

**Comment by jeroen** [comment]
Fair enough, thanks for giving it a try.
