### ISSUE TITLE
roxygen2::roxygenize() trying to process too many files

### ISSUE THREAD

**Issue by harrelfe** [r-lib/roxygen2#1583]
I'm using 7.3.1 on MacOS.  I have recently switched from Linux where I never had a problem like this.  `roxygenize` is trying to process all the `.s` files in my `R` directory for a package when before it only processed my `.r` files, which was the desired behavior.  I have a lot of old R functions for which I had manually created `.Rd` files.  `roxygenize` is throwing a lot of errors because of the lack of `oxygenize` markups in the `.s` files.  How do I get the old behavior of ignoring these files?

**Comment by dmurdoch** [comment]
This issue was discussed here:  https://stackoverflow.com/a/77891486 .  The problem is that Frank was using the default roclets, which include `"namespace"`, but he had a hand-written `NAMESPACE` file.  It appears that in this situation `roxygenize()` will do the necessary calculations to produce the `NAMESPACE` and issue warnings like

    areg.s:432: S3 method `plot.areg` needs @export or @exportS3method tag.

Then eventually it detects that `NAMESPACE` is already present and not overwriteable, so it is left unchanged.  Earlier versions did similar things without issuing those warnings, so it appeared the .s files were ignored.

I'd suggest putting the test for `NAMESPACE` earlier in the processing, so that the namespace roclet isn't even started if a hand-written `NAMESPACE` file is present.

**Comment by harrelfe** [comment]
Thanks so much.  Restricting to `roclets='rd'` fixed it.
