### ISSUE TITLE
Possibility to force export instead of s3method in NAMESPACE

### ISSUE THREAD

**Issue by skranz** [r-lib/roxygen2#243]
I use the current roxygen2 Version 3.1.0 which seems to be current version on CRAN. I have a package stringtools (https://github.com/skranz/stringtools) that has function names like str.find, which is NOT used as an S3 method for the class str. (I agree that the naming ambiguity is a bit unfortunate, but I guess such naming ambiguity happens fairly often in R)
Older versions of roxygen2 created correct export statements in the NAMESPACE file, like:

```
export(str.find)
```

My version 3.1.0 instead creates:

```
S3method(str,find)
```

which makes my package not run properly.
Is there some way to force roxygen2 to create export statements instead of S3method statements? Otherwise, I always have to manually keep the NAMESPACE file up-to-date, which is not as convenient as it could be.

**Comment by MichaelChirico** [comment]
FWIW, here's an edge case where this is apparently necessary

If my package `foo` makes a function `foo.bar`, and `foo` Depends on a package `baz` that exports a `foo` generic, but my `foo.bar` _is not intended to be a `foo` method_, I need to do `@export foo.bar`.

Specifically in my case there's a function `cv.somename`, named to evoke `glmnet::cv.glmnet()`, which AFAIK is _not_ a `cv` method for class `glmnet`. The package also (incidentally) depends on a package exporting `cv` and declaring it a generic. Because the dependency is transitive/incidental, it took a while to realize why `loadNamespace()` was failing (couldn't find object `cv`)...

This basically comes down to the well-known problem with S3 to begin with where `.` is part of valid names as well as the method-class separator. Obviously `snake_case` is better but we don't always have that flexibility :)

**Comment by MonteShaffer** [comment]
Debating over "edge cases" is not the point.  Extensibility is the point.  If I want to use a point `.`, it is allowable by R syntax.  I should not have to justify my "why", just an answer on how. I don't have to marry myself to the religion of `snake_case`!

If I want to use `str.find` as my fn.name and paste it directly into R, it automatically gets `S3` listed.  How do I delist it from that namespace?  That is, I want to use `str.find` independent of namespace("str")?  Is there a `delist` function?

**Comment by gaborcsardi** [comment]
If you don't add `@export` to `str.find()`, then roxygen2 does not write anything about it in `NAMESPACE`.

If you want `export(str.find)` in the `NAMESPACE`, then write:

```
#' @export str.find

str.find <- function() {
  # ...
}
```

Is this what you need?

**Comment by spgarbet** [comment]
The base R statistical tests all use a "." in their name, e.g. `wilcox.test`. If I were to maintain consistency with base R when adding a statistical test, then I'm in this conflict between "shouldn't use '.' in function names" and "best to maintain consistency to minimize user surprise".
