### ISSUE TITLE
Document the $clone() method in an R6 class

### ISSUE THREAD

**Issue by hongyuanjia** [r-lib/roxygen2#956]
Current R6 support is super fantastic.

Every R6 class will have a `$clone()` method by default. How can I explicitly document that method just like other normal method, if I want to use builtin `$clone()` method?

**Comment by gaborcsardi** [comment]
We left out `clone()` (https://github.com/r-lib/roxygen2/blob/08401f1568fb9655b8d340eb9880b327aad5fcb2/R/object-r6.R#L30), because it does not seem to be a way to tell if it was user-defined or the default, and I thought that we would implement some way to add it manually if it was user defined.

I think for now, you can have a paragraph that explains that the class has a custom `clone()` method.

Do you think it is better to add it, even if it was the default?

**Comment by hongyuanjia** [comment]
Yes, I still think it is useful even if it is the default. This is because an R6 object has reference semantics, which is different from normal R objects that most user handles in their workflow. Document `$clone()` method and let them know `$clone()` is a good way to explain this and avoid some confusing.

I agree I can have a paragraph to document the `$clone()` method, which is what I did before the great R6 PR merged in roxygen2. But with the new method of documenting R6, adding an extra paragraph to explain `$clone()` seems a little bit wired and would not fit nicely into current formatting.

Also, for me I only customize the `deep_clone()` method in `private` and leave the `public` `clone()` method as default. In this case, there is still no customized `$clone()` method, but it would be better to document the actual behavior when `deep` argument is set to `TRUE` in `$clone()`
