### ISSUE TITLE
Functions get exported even without @export

### ISSUE THREAD

**Issue by sboehringer** [r-lib/roxygen2#978]
I am not sure whether this is intended behavior or not. My workflow is as follows: I have a number of R-scripts that I use in several R-packages. I have documented functions therein using roxygen2 but I do not use @export to export them. I do not export these functions. If I document the package using document from devtools or roxigenize from roxygen2, Rd-files are generated for these functions. If I load the package, the documented functions are available in global namespace even though they do not appear in the NAMESPACE file.

The expected behavior would be that no Rd files are generated for functions without an @export tag. Also they should remain internal to the package and should not be exported to the global environment.

Depending what the truly expected behavior is, this would be either a bug report. Otherwise it would be a feature request to allow the documentation of functions in roxygen2-style but to be able to suppress Rd-file generation, say, with an @ignore tag.

**Comment by gaborcsardi** [comment]
Rd files are generated for functions without an `@export` tag, because people often want to document internal functions. 

The ignore tag is called `@noRd`. 

Also look at `@keywords internal` which is an alternative: it will generate an Rd file, but will not include it in the index, so people will only find it if they `?` that function directly.
