### ISSUE TITLE
Include Rmd in an user defined section

### ISSUE THREAD

**Issue by maelle** [r-lib/roxygen2#988]
The new includeRmd feature is awesome, thanks! :star2: 

I read "Example: @includeRmd path description. This currently does not work with user defined sections (created with @section)." in [the vignette](https://roxygen2.r-lib.org/articles/rd.html#including-external--rmd-md-files) and am therefore opening an issue to request the feature. :wink:

I would like to use it in particular to be able to include content _after_ the "Value" and "Examples" section without needing to write a level 1 header in the Rmd. The Details section comes before "Value" and "Examples" which is not optimal for the user reading the docs.

Not sure if my use case is helpful to know about: I have an Rmd with all the details the user needs to know about authorization in a package, whose content is under a level 3 header in the README and vignette (via [the approach described in this blog post](https://www.garrickadenbuie.com/blog/dry-vignette-and-readme/)), but should be an user-defined section in the man page. At the moment I can't do that without having a level 1 header in the Rmd, that I'd somehow strip in a previous chunk in the README and vignette.

**Comment by hadley** [comment]
I don't think you can insert content after the examples section.

**Comment by gaborcsardi** [comment]
I'll take a look at this before the release. To include `.Rmd`s into user defined `@section`s I mean. 

The order of the sections in the formatted manual is beyond what we can do.

**Comment by gaborcsardi** [comment]
Yeah, so this is not so easy to fix, because roxygen tags cannot be embedded. The `@includeRmd` tag would have to know which `@section` tag came before it, which is probably possible to implement, but it seems messy.

I think with the new markdown code support it will be much easier to solve these issues. E.g.

```
#' @section Title:
#' Some text.
#'
#' ```{r child = "man/roxygen/child.Rmd"}
#' ```
#'
#' More text.
```

A child document like this will be always embedded into the current tag.
